development:
  adapter: postgresql
  encoding: utf8
  database: checker_development
  pool: 5
  username: checker
  password:
  port: 5433

test:
  adapter: postgresql
  encoding: utf8
  database: checker_test
  pool: 5
  username: checker
  password:
  port: 5433
